### ISSUE TITLE
the tree structure of the directory

### ISSUE THREAD

**Issue by Yao1up** [svyas23/cross-view-action#1]
I'm confused about running this code，and what commands should I run. Could you provide me with the tree structure of the directory, such as the folder name.

**Comment by vyzuer** [comment]
You can do a 'python train.py' to start a training, and then 'python test.py' to test the model.

Let me know if there is any issue.

**Comment by Yao1up** [comment]
> You can do a 'python train.py' to start a training, and then 'python test.py' to test the model.
> 
> Let me know if there is any issue.
Thank you very much for your answer !
when I run train.py, there is an error shows that:
'' 
Traceback (most recent call last):
  File "D:/Workplace/Code/cross/cross-view-action/train.py", line 115, in <module>
    train_model()
  File "D:/Workplace/Code/cross/cross-view-action/train.py", line 55, in train_model
    model.load_weights(params.model_weights1, by_name=True)
  File "D:\Software\Python\Python3.6.8\lib\site-packages\keras\engine\topology.py", line 2658, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "D:\Software\Python\Python3.6.8\lib\site-packages\h5py\_hl\files.py", line 427, in __init__
    swmr=swmr)
  File "D:\Software\Python\Python3.6.8\lib\site-packages\h5py\_hl\files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'test/2views_101-0.604319-0.851-1.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
''

**Comment by Yao1up** [comment]
> > You can do a 'python train.py' to start a training, and then 'python test.py' to test the model.
> > Let me know if there is any issue.
> > Thank you very much for your answer !
> > when I run train.py, there is an error shows that:
> > ''
> > Traceback (most recent call last):
> > File "D:/Workplace/Code/cross/cross-view-action/train.py", line 115, in 
> > train_model()
> > File "D:/Workplace/Code/cross/cross-view-action/train.py", line 55, in train_model
> > model.load_weights(params.model_weights1, by_name=True)
> > File "D:\Software\Python\Python3.6.8\lib\site-packages\keras\engine\topology.py", line 2658, in load_weights
> > with h5py.File(filepath, mode='r') as f:
> > File "D:\Software\Python\Python3.6.8\lib\site-packages\h5py_hl\files.py", line 427, in **init**
> > swmr=swmr)
> > File "D:\Software\Python\Python3.6.8\lib\site-packages\h5py_hl\files.py", line 190, in make_fid
> > fid = h5f.open(name, flags, fapl=fapl)
> > File "h5py_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
> > File "h5py_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
> > File "h5py\h5f.pyx", line 96, in h5py.h5f.open
> > OSError: Unable to open file (unable to open file: name = 'test/2views_101-0.604319-0.851-1.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
> > ''
I cannot find the weight files, could the code provided it ?
model_weights1='test/2views_101-0.604319-0.851-1.h5'
model_weights='test/2views_303-0.735551-0.801-1.h5'
model_weights2='test/2views_063-0.702150-0.851-1.h5'

**Comment by svyas23** [comment]
> 
> 
> > > You can do a 'python train.py' to start a training, and then 'python test.py' to test the model.
> > > Let me know if there is any issue.
> > > Thank you very much for your answer !
> > > when I run train.py, there is an error shows that:
> > > ''
> > > Traceback (most recent call last):
> > > File "D:/Workplace/Code/cross/cross-view-action/train.py", line 115, in
> > > train_model()
> > > File "D:/Workplace/Code/cross/cross-view-action/train.py", line 55, in train_model
> > > model.load_weights(params.model_weights1, by_name=True)
> > > File "D:\Software\Python\Python3.6.8\lib\site-packages\keras\engine\topology.py", line 2658, in load_weights
> > > with h5py.File(filepath, mode='r') as f:
> > > File "D:\Software\Python\Python3.6.8\lib\site-packages\h5py_hl\files.py", line 427, in **init**
> > > swmr=swmr)
> > > File "D:\Software\Python\Python3.6.8\lib\site-packages\h5py_hl\files.py", line 190, in make_fid
> > > fid = h5f.open(name, flags, fapl=fapl)
> > > File "h5py_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
> > > File "h5py_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
> > > File "h5py\h5f.pyx", line 96, in h5py.h5f.open
> > > OSError: Unable to open file (unable to open file: name = 'test/2views_101-0.604319-0.851-1.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
> > > ''
> > > I cannot find the weight files, could the code provided it ?
> > > model_weights1='test/2views_101-0.604319-0.851-1.h5'
> > > model_weights='test/2views_303-0.735551-0.801-1.h5'
> > > model_weights2='test/2views_063-0.702150-0.851-1.h5'

You can set 'weights=False' in line number 22.
