### ISSUE TITLE
Training dataset

### ISSUE THREAD

**Issue by Yao1up** [svyas23/cross-view-action#3]
hello, the NTU-RGB+D dataset is named as "S001C001P001R001A001", but I check the document in the path of "data/train.list", it shows that "18/S005P017R002A018 100 100 100", which only has the information of S,P,R and A, and missed the information of the ID of camera, that is "C". I am very confused, thank you for your reply.

**Comment by vyzuer** [comment]
The camera id should be inside the folder, named as 1 2 and 3. The last three items are corresponding number of frames from each viewpoint/camera-id.

**Comment by svyas23** [comment]
I have camera id as views as subfolders inside this folder.
