### ISSUE TITLE
Asking for the frame extraction code

### ISSUE THREAD

**Issue by tauruswcc** [svyas23/cross-view-action#4]
Hi,

Thank you for providing the codes and trained models. I would like to test the accuracy of the trained models. I downloaded the NTU-RGB+D dataset. Could you please kindly share the frame extraction code? Thank you so much!

**Comment by Demi778** [comment]
Hey there! Can anyone share the frame extraction code with me ? Thank uuuuu so much !

**Comment by tauruswcc** [comment]
@Demi778 Hi, you may try this.
- Frame extraction code by Chengcheng Wang

#To import modules
import os
import subprocess

video_root_path = '/media/user/T7_1/wangcc/NTU RGB+D'#root path to videos
frame_root_path = '/media/user/T7_1/wangcc/NTU RGB+D_frames'#root path to store RGB frames

for root, _, videos in os.walk(video_root_path):
	if videos:
		for video in videos:

			## to create directory to store RGB frames
			video_name = video.split('_')[0]
			#print('video_name is:', video_name)
			action_label = str(int(video_name[-2:]))#action_label is str
			camera_id = video_name[7]
			subfolder_name = video_name[:4] + video_name[8:]
			frame_path = frame_root_path + '/' + action_label + '/' + subfolder_name + '/' + camera_id
			#to create folders
			isExists=os.path.exists(frame_path)
			if not isExists:
				os.makedirs(frame_path)

			## to extract and save RGB frames
			video_file_path = root + '/' + video#path to video
			cmd = 'ffmpeg -i \"{}\" -s 240*135 \"{}/frame_%05d.jpg\"'.format(video_file_path, frame_path)
			print(cmd)
			subprocess.call(cmd, shell=True)
			print('\n')

- Then you may need to make the following changes in the data_generator file:
`r_id = np.random.randint(1, fcount-(self.num_frames+1)*skip_rate)
f_path = os.path.join(params.rgb_data, vid, str(random_view), 'frame_{:05d}.jpg'.format(r_id))`

**Comment by Demi778** [comment]
> @Demi778 Hi, you may try this.
> 
> * Frame extraction code by Chengcheng Wang
> 
> # To import modules
> import os import subprocess
> 
> video_root_path = '/media/user/T7_1/wangcc/NTU RGB+D'#root path to videos frame_root_path = '/media/user/T7_1/wangcc/NTU RGB+D_frames'#root path to store RGB frames
> 
> for root, _, videos in os.walk(video_root_path): if videos: for video in videos:
> 
> ```
> 		## to create directory to store RGB frames
> 		video_name = video.split('_')[0]
> 		#print('video_name is:', video_name)
> 		action_label = str(int(video_name[-2:]))#action_label is str
> 		camera_id = video_name[7]
> 		subfolder_name = video_name[:4] + video_name[8:]
> 		frame_path = frame_root_path + '/' + action_label + '/' + subfolder_name + '/' + camera_id
> 		#to create folders
> 		isExists=os.path.exists(frame_path)
> 		if not isExists:
> 			os.makedirs(frame_path)
> 
> 		## to extract and save RGB frames
> 		video_file_path = root + '/' + video#path to video
> 		cmd = 'ffmpeg -i \"{}\" -s 240*135 \"{}/frame_%05d.jpg\"'.format(video_file_path, frame_path)
> 		print(cmd)
> 		subprocess.call(cmd, shell=True)
> 		print('\n')
> ```
> 
> * Then you may need to make the following changes in the data_generator file:
>   `r_id = np.random.randint(1, fcount-(self.num_frames+1)*skip_rate) f_path = os.path.join(params.rgb_data, vid, str(random_view), 'frame_{:05d}.jpg'.format(r_id))`


WOW!!It's so kind of you ! But,do you have the NTU-RGB+D dataset? I really need the part of RGB-videos~~Thank u very much !!!!

**Comment by tauruswcc** [comment]
@Demi778 To download the NTU-RGB+D dataset, you have to make request first on their official website.

**Comment by Demi778** [comment]
> @Demi778 To download the NTU-RGB+D dataset, you have to make request first on their official website.

Okk!! You really help me a lot!! Thank u !

**Comment by Demi778** [comment]
> @Demi778 To download the NTU-RGB+D dataset, you have to make request first on their official website.
I'm sorry but, should I change the data_generator file or the data_generetor1 file ?

**Comment by tauruswcc** [comment]
@Demi778 Actually, I did not use the data_generator file directly. I modified the file based on my own test conditions.

**Comment by Demi778** [comment]
> @Demi778 Actually, I did not use the data_generator file directly. I modified the file based on my own test conditions.

Yes, I got it. But I don't know why I can't use your code...it just cuts to an empty file when it finishes running. But don't worry about that, I can try other frame clipping codes. Is there anything to pay attention to?
And, may I ask you one more question? I found train.list in the code and I wonder if the video frames should be named the last three items in the picture?
I want to use a part of the dataset to participate in model training first, but I don't know how to correspond to the form of train.list.   Can I have your advice?
![image](https://user-images.githubusercontent.com/76242492/148942159-dd79d10b-ca59-4792-bbff-64ddc6897906.png)

**Comment by vyzuer** [comment]
These are number of frames in the videos captured from the three
viewpoints, v1 v2 v3. Each row is an instance if action which is captured
from three viewpoints. These are used during data loading.

**Comment by Demi778** [comment]
> These are number of frames in the videos captured from the three viewpoints, v1 v2 v3. Each row is an instance if action which is captured from three viewpoints. These are used during data loading.

Thank u for your reply~ Are there any requirements for the order of the data in train.list?
![1641907806(1)](https://user-images.githubusercontent.com/76242492/148951336-79859e80-a462-4f98-add2-148efbe7ec03.png)
From the picture, we can see that the list first start with 18, and the back is 12. Is there a specific ordering requirement?  Why not arrange them in the order 1,2,3....?

**Comment by vyzuer** [comment]
There is no such requirement, the list is randomly shuffled anyways during
training every epoch.
