### ISSUE TITLE
Tensorflow and Keras versions

### ISSUE THREAD

**Issue by tauruswcc** [svyas23/cross-view-action#5]
Hi,

Thank you for sharing the codes and trained model.

I've been testing the trained model using Keras 2.4.3 and Tensorflow 2.3.2, but I came across several errors. I think it is because of different package versions. Could you please tell me the preferred versions for Keras and Tensorflow? Thank you so much for your great help!

**Comment by sydat2701** [comment]
> 

Hi guy,
Did you solve this problem? Could you please tell me those versions of Keras and Tensorflow? 
Thank you so much for your help!

**Comment by tauruswcc** [comment]
@sydat2701 Hi, I still did not know the Keras and Tensorflow versions used in the original implementation. I was using Tensorflow 2.7 with inbuilt Keras, and modified the original implementation accordingly. Thank you.
